const SECTION_HEADING_STYLE: React.CSSProperties = {
  fontSize: '18px',
  fontWeight: 600,
  marginTop: '32px',
  marginBottom: '8px',
};

const BODY_STYLE: React.CSSProperties = {
  fontSize: '14px',
  lineHeight: 1.7,
  color: 'var(--color-text-muted)',
};

export const metadata = {
  title: 'Privacy Policy | PropFlow',
};

export default function PrivacyPolicyPage() {
  return (
    <div
      style={{
        maxWidth: '720px',
        margin: '0 auto',
        padding: '48px 24px 96px',
      }}
    >
      <h1 style={{ fontSize: '28px', fontWeight: 700, marginBottom: '4px' }}>Privacy Policy</h1>
      <p style={{ fontSize: '13px', color: 'var(--color-text-muted)', marginBottom: '24px' }}>
        Last updated: September 17, 2026
      </p>

      <p style={BODY_STYLE}>
        This Privacy Policy describes how PropFlow (&ldquo;PropFlow&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) collects, uses, and
        protects information when you use our manager web application, our tenant mobile
        application, and related services (collectively, the &ldquo;Service&rdquo;). PropFlow is a
        multi-tenant property management platform used by property management companies
        (&ldquo;Organizations&rdquo;) and the tenants, owners, and staff associated with those Organizations.
      </p>

      <h2 style={SECTION_HEADING_STYLE}>Information We Collect</h2>
      <p style={BODY_STYLE}>
        We collect information you provide directly, including account details (name, email,
        phone), lease and tenancy information, payment and bank account details processed
        through our payment provider, maintenance/work order submissions (including photos you
        choose to upload), in-app messages, and documents you upload or that are shared with you.
        We also collect information generated by your use of the Service, such as login activity
        and device push-notification tokens.
      </p>

      <h2 style={SECTION_HEADING_STYLE}>How We Use Information</h2>
      <p style={BODY_STYLE}>
        We use collected information to operate the Service: to authenticate accounts, process
        rent and other payments, route and track maintenance requests, deliver messages and
        notifications, generate statements and reports for property owners and managers, and
        maintain the security and integrity of the Service. Data belonging to one Organization is
        never shared with another Organization.
      </p>

      <h2 style={SECTION_HEADING_STYLE}>Payment Information</h2>
      <p style={BODY_STYLE}>
        Rent and other payments are processed through Stripe. PropFlow does not store full bank
        account or card numbers &mdash; payment method details are handled directly by Stripe under
        its own privacy policy and PCI-compliant infrastructure. We retain only the payment
        records, amounts, and statuses needed to maintain your ledger and payment history.
      </p>

      <h2 style={SECTION_HEADING_STYLE}>Data Sharing</h2>
      <p style={BODY_STYLE}>
        We share information with service providers who help us operate the Service &mdash; including
        Stripe (payments), Supabase (authentication and file storage), Resend (email), Twilio
        (SMS), and Expo (push notifications) &mdash; solely to provide their respective functions. We do
        not sell personal information. Information may also be disclosed if required by law.
      </p>

      <h2 style={SECTION_HEADING_STYLE}>Data Retention &amp; Security</h2>
      <p style={BODY_STYLE}>
        We retain information for as long as your account or your Organization&apos;s account remains
        active, or as needed to comply with legal and accounting obligations. We use
        industry-standard safeguards, including encrypted storage for sensitive identifiers,
        access controls scoped to your Organization, and signed, time-limited URLs for document
        and file access.
      </p>

      <h2 style={SECTION_HEADING_STYLE}>Your Choices</h2>
      <p style={BODY_STYLE}>
        You may update your profile information at any time from your account settings. To
        request deletion of your account or data, contact your property management Organization
        directly, or reach out to us using the contact information below.
      </p>

      <h2 style={SECTION_HEADING_STYLE}>Children&apos;s Privacy</h2>
      <p style={BODY_STYLE}>
        The Service is not directed to children under 13, and we do not knowingly collect
        personal information from children under 13.
      </p>

      <h2 style={SECTION_HEADING_STYLE}>Changes to This Policy</h2>
      <p style={BODY_STYLE}>
        We may update this Privacy Policy from time to time. We will post the updated policy on
        this page with a revised &ldquo;Last updated&rdquo; date.
      </p>

      <h2 style={SECTION_HEADING_STYLE}>Contact Us</h2>
      <p style={BODY_STYLE}>
        If you have questions about this Privacy Policy, please contact your property management
        Organization, or reach PropFlow support through the contact details provided in the app.
      </p>
    </div>
  );
}
